### ISSUE TITLE
tell me how import that dashboard in superset?

### ISSUE THREAD

**Issue by johnfelipe** [cnstlungu/portable-data-stack-airflow#2]
https://raw.githubusercontent.com/cnstlungu/demo-bi-docker/master/resources/superset.gif

**Comment by cnstlungu** [comment]
I've added an example dashboard to the repository so it should work now.

Generally:
Exporting: run `superset export-dashboards > dashboard.json`
Importing: run `superset import-dashboards -p ./dashboard.json`

**Comment by cnstlungu** [comment]
dashboard added
