### ISSUE TITLE
dashboard superset missing

### ISSUE THREAD

**Issue by johnfelipe** [cnstlungu/portable-data-stack-airflow#3]
![SNAG-1302](https://user-images.githubusercontent.com/428820/174409133-df4891f6-e0dc-44d6-a01c-e1c08aee4fc4.png)

**Comment by cnstlungu** [comment]
Please check if the Airflow DAGs are still running. Until they are completed, there is no data in the data warehouse for Superset to display in the dashboards.

**Comment by johnfelipe** [comment]
pls view this 10 min video with putty logs and chrome view with superset and airflow, still not work DATA:

`oltp_1       | 2022-06-20 16:08:48.826 UTC [204] FATAL:  role "root" does not exist`

and

`airflow_1    | [2022-06-20 16:09:06,710] {manager.py:512} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.can_create User
`

https://drive.google.com/file/d/1IRwd-kNYFHKtJ802wJjIYTSriQEEUdbn/view?usp=drivesdk

**Comment by cnstlungu** [comment]
![image](https://user-images.githubusercontent.com/10930578/174652733-a6e10068-60e9-450d-9b11-214f0d8f9281.png)

At this point here, the two light-green statuses show that dags haven't completed running.

Specifically the `load-data-warehouse` DAG needs to complete as it's loading the Data Warehouse.

If you're stuck in an unclear state, I would clean up `docker-compose down -v` then start it again `docker-compose up --build`

**Comment by johnfelipe** [comment]
https://gist.github.com/e815649fafda5ee60d7c430f3e9f7f09

wich command need to do with that log?

**Comment by johnfelipe** [comment]
![SNAG-0010](https://user-images.githubusercontent.com/428820/177626701-fe6d799e-ad59-46b0-be48-3f304c63592b.png)

what i need to do, in that case?

**Comment by cnstlungu** [comment]
In your screenshot two of the DAGs have tasks (steps) that are failing or retrying.  Click on the DAG that has failed (red circles) or retrying (orange) tasks, then view their logs to understand what went wrong.

**Comment by cnstlungu** [comment]
If you're stuck in an unclear state, I would clean up `docker-compose down -v` then start it again `docker-compose up --build`

**Comment by cnstlungu** [comment]
Rewritten the DW loading part using dbt. Closing this issue.
